sudo: required

services:
  - docker
  - postgresql

language: ruby

rvm:
  - 2.2.3

before_install:
  - docker-compose build
  - docker-compose up -d
  - docker build -t denmanjd/rails_app .
  - docker ps
env:
  - RAILS_ENV=test
script:
  - docker exec railsdockervagrantdevkit_web_1 bin/rake db:create db:migrate
  - docker exec railsdockervagrantdevkit_web_1 bin/bundle exec rspec

install:
  - docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
  - docker push denmanjd/rails_app