db:
  image: postgres
web:
  build: . #builds container from colocated Dockerfile in root of directory
  command: bundle exec unicorn -p 3000
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - db
